services:
  app:
    image: app-image 
    build: ./app/
    container_name: app
    depends_on:
      - db
      - transaction
      - artemis  
    ports:
      - 8779:8779
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2281337
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TRANSACTION_SERVICE_HOST=transaction
      - SPRING_ARTEMIS_USER=artemis
      - SPRING_ARTEMIS_PASSWORD=2281337
      - SPRING_ARTEMIS_BROKERURL=tcp://artemis:61616
    volumes:
      - xml-data:/data

  transaction:
    image: transaction-image
    build: ./transaction_service/
    container_name: transaction
    depends_on:
      - db
      - artemis 
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2281337
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_ARTEMIS_USER=artemis
      - SPRING_ARTEMIS_PASSWORD=2281337
      - SPRING_ARTEMIS_BROKERURL=tcp://artemis:61616

  db:
    image: postgres:15
    container_name: db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2281337
    volumes:
      - postgres-data:/var/lib/postgresql/data

  artemis:
    image: vromero/activemq-artemis
    container_name: artemis
    ports:
      - 8161:8161
      - 61616:61616
      - 5762:5762
    environment:
      - ARTEMIS_USERNAME=artemis
      - ARTEMIS_PASSWORD=2281337


volumes:
  postgres-data:
  xml-data:
