services:

  config:
    image: config-image
    build: ./configserver/
    container_name: config
    depends_on:
      - consul
    ports:
      - 8888:8888
    environment:
      - spring_cloud_config_server_git_uri=https://github.com/AliIbadullayev/Cashback-Config-Repository
      - SPRING_CLOUD_CONSUL_HOST=consul
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config:8888" ]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    image: app-image 
    build: ./app/
    container_name: app
    depends_on:
      - db
      - transaction
      - artemis
      - config
      - consul
    ports:
      - 8779:8779
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2281337
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TRANSACTION_SERVICE_HOST=transaction
      - SPRING_ARTEMIS_USER=artemis
      - SPRING_ARTEMIS_PASSWORD=2281337
      - SPRING_ARTEMIS_BROKERURL=tcp://artemis:61616
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config:8888/config
    volumes:
      - xml-data:/data

  transaction:
    image: transaction-image
    build: ./transaction_service/
    container_name: transaction
    depends_on:
      - db
      - artemis
      - config
      - consul
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2281337
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_ARTEMIS_USER=artemis
      - SPRING_ARTEMIS_PASSWORD=2281337
      - SPRING_ARTEMIS_BROKERURL=tcp://artemis:61616
      - SPRING_CLOUD_CONSUL_HOST=consul


  gateway:
    image: apigateway-image
    build: ./apigateway/
    container_name: gateway
    depends_on:
      - db
      - artemis
      - consul
    ports:
      - 8090:8090
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul


  db:
    image: postgres:15
    container_name: db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2281337
    volumes:
      - postgres-data:/var/lib/postgresql/data


  artemis:
    image: vromero/activemq-artemis
    container_name: artemis
    ports:
      - 8161:8161
      - 61616:61616
      - 5762:5762
    environment:
      - ARTEMIS_USERNAME=artemis
      - ARTEMIS_PASSWORD=2281337



  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500



volumes:
  postgres-data:
  xml-data:
